version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0 # This disables version updates, security updates are still created

  # Maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0 # This disables version updates, security updates are still created

  # NPM
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0 # This disables version updates, security updates are still created

  # Dev Containers
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0 # This disables version updates, security updates are still created

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0 # This disables version updates, security updates are still created

  # Python (Pip)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0 # This disables version updates, security updates are still created

  # Terraform
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0 # This disables version updates, security updates are still created
